name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Adds-On
      run: |
        sudo apt-get -y install xsel xclip wl-clipboard

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make
#       run: go build -v ./...

    - name: Test
      run: make test
#       run: go test -v ./...
