name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Adds-On
      run: |
        sudo apt-get -y install xsel

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        echo "Build crypt"
        cd crypt
        go build
        cd -

        echo "Build vault"
        cd vault
        go build
        cd -

        echo "Build CLI"
        cd cli
        make
        cd -

        echo "Build server"
        cd server
        make
        cd -

        echo "Build term"
        cd term
        make
        cd -

        echo "Build wasm"
        cd wasm
        make
        cd -

    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        SKIP_CLIPBOARD_TEST: '1'

    - name: Test
      run: |
        echo "Test crypt"
        cd crypt
        go test
        cd -

        echo "Test vault"
        cd vault
        go test
        cd -

        echo "Test CLI"
        cd cli
        make test
        cd -

        echo "Test server"
        cd server
        make test
        cd -

        echo "Test term"
        cd term
        make test
        cd -

    - name: Build fyne
      run: |
        echo "build fyne"
        curl -ksLO https://github.com/fyne-io/fyne/archive/refs/tags/v2.2.2.tar.gz
        tar xfz v2.2.2.tar.gz
        cd fyne-2.2.2/cmd/fyne
        pwd
        ls
        go build
        ls
        cp fyne ../../../
        cd -
        pwd
        ls -al $PWD

    - name: Add credentials
      run: |
        pwd
        cd ui
        cat > credentials.env << EOF
        DROPBOX_CLIENT_ID=${{ secrets.DROPBOX_CLIENT_ID }}
        DROPBOX_CLIENT_SECRET=${{ secrets.DROPBOX_CLIENT_SECRET }}
        DROPBOX_PORT=${{ secrets.DROPBOX_PORT }}
        EOF
        sed -i -e "s,^[[:space:]]*,,g" credentials.env
        cat > rclone.conf << EOF
        [local]
        type = local
        [dropbox]
        type = dropbox
        env_auth = true
        EOF
        sed -i -e "s,^[[:space:]]*,,g" rclone.conf
        cd -

    - name: Build-UI
      run: |
        pwd
        export PATH=$PATH:$PWD
        cd ui
        mkdir ecm_{amd64,darwin,power8,arm64,windows}
        sudo apt-get -y install xorg-dev

        #echo "Power8 build"
        #make build_power8;  mv ecm ecm_power8

        echo "ARM64 build"
        make build_arm64;   mv ecm ecm_arm64

        echo "Windows build"
        make build_windows; mv ecm ecm_windows

        echo "AMD64 build"
        make build_amd64;   mv ecm ecm_amd64

        echo "Tar all builds"
        tar cfz ../ecm_app.tar.gz ecm_amd64 ecm_arm64 ecm_windows
        #tar cfz ../ecm_app.tar.gz ecm_amd64 ecm_power8 ecm_arm64 ecm_windows ecm.app
