name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Adds-On
      run: |
        sudo apt-get -y install xsel

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        echo "Build crypt"
        cd crypt
        go build
        cd -

        echo "Build vault"
        cd vault
        go build
        cd -

        echo "Build CLI"
        cd cli
        make
        cd -

        echo "Build server"
        cd server
        make
        cd -

        echo "Build term"
        cd term
        make
        cd -

        echo "Build wasm"
        cd wasm
        make
        cd -

    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        SKIP_CLIPBOARD_TEST: '1'

    - name: Test
      run: |
        echo "Test crypt"
        cd crypt
        go test
        cd -

        echo "Test vault"
        cd vault
        go test
        cd -

        echo "Test CLI"
        cd cli
        make test
        cd -

        echo "Test server"
        cd server
        make test
        cd -

        echo "Test term"
        cd term
        make test
        cd -
